Form/records
WildCodeSchool/btz-0321-aeviso-client pull request #30
Opened 2021-06-14 14:23 UTC by Chabelle78

CRUD VIEWS DONE

2021-06-14 14:32 UTC, ThomasBarrial approved these changes

2021-06-15 07:51 UTC, MatthiasWanner requested changes
Just have to delete zipcode field because it does not work

2021-06-15 07:51 UTC, MatthiasWanner commented on src/components/company/CreateCompanyForm.tsx
> +          Zip Code:
Delete this input. It does not work.

2021-06-15 11:22 UTC, MatthiasWanner approved these changes

2021-06-16 09:03 UTC, Karnak19 approved these changes

2021-06-16 09:03 UTC, Karnak19 commented on src/components/company/Company.tsx
> +      </p>
Maybe create an error component that you can use across all the application (but it will be another branch ;) )

2021-06-16 09:03 UTC, Karnak19 commented on src/components/company/CreateCompanyForm.tsx
> +      console.log(error);
Remove this console.log

2021-06-16 11:54 UTC, merged