Dark mode
WildCodeSchool/btz-0321-aeviso-client pull request #68
Opened 2021-06-26 17:27 UTC by ThomasBarrial

2021-06-26 17:29 UTC, ThomasBarrial commented
Don't merge before redux and layout2 !!!!

2021-06-27 06:02 UTC, MatthiasWanner reviewed
Is it normal ?
<img width="1438" alt="Capture d’écran 2021-06-27 à 07 58 27" src="https://user-images.githubusercontent.com/79398461/123534498-d0151c80-d71d-11eb-84ea-d94e7eb57cb3.png">

<img width="1435" alt="Capture d’écran 2021-06-27 à 07 59 05" src="https://user-images.githubusercontent.com/79398461/123534518-f0dd7200-d71d-11eb-8113-82649bf6f036.png">

2021-06-27 06:10 UTC, MatthiasWanner requested changes

2021-06-27 06:10 UTC, MatthiasWanner commented on src/views/HomePage.tsx
> +        className="w-12/12 sm:w-full mt-5 flex items-center flex-col text-white font-roboto text-xl sm:text-2xl"
w-12/12 & sm:w-full are egal.
In desktop mode, login form take full screen centered

2021-06-27 06:10 UTC, MatthiasWanner commented on src/components/Modal.tsx
> +      <div className="p-10 w-10/12 sm:5/12 shadow-mainShadow flex flex-col justify-start z-50 text-white bg-black rounded-md break-all">
You've forgot a w "sm:w-5/12"

2021-07-01 10:55 UTC, MatthiasWanner approved these changes

2021-07-01 11:29 UTC, merged