Dev
WildCodeSchool/btz-0321-aeviso-client pull request #74
Opened 2021-07-04 10:29 UTC by MatthiasWanner

Update master with dev branch

2021-07-04 14:31 UTC, MatthiasWanner commented on src/components/NavBar.tsx/ADMIN.tsx
> +import React from 'react';
Please rename folder by NavBar (delete ".tsx")

2021-07-04 14:31 UTC, MatthiasWanner commented on src/components/NavBar.tsx/ADMIN.tsx
> +function ADMIN({ Home, Rapport, Réglages, NouveauRapport, handleClose }: ISPNavbar): JSX.Element {
Règlages, NouveaRapport, Rapport? Please use english for your props name

2021-07-04 14:31 UTC, MatthiasWanner commented on src/components/NavBar.tsx/SUPERADMIN.tsx
> +function SUPERADMIN({ Home, Rapport, Réglages, handleClose }: ISPNavbar): JSX.Element {
Idem, english props name

2021-07-04 14:31 UTC, MatthiasWanner commented on src/components/NavBar.tsx/USER.tsx
> +function USER({ NouveauRapport, Home, Rapport, Réglages, handleClose }: ISPNavbar): JSX.Element {
Props name in english

2021-07-04 14:31 UTC, MatthiasWanner commented on src/components/NavBar.tsx/sideBar.tsx
> +import Réglages from '../../../media/icons/Settings.svg';
English

2021-07-04 14:55 UTC, MatthiasWanner reviewed
All is ok for me

2021-07-05 07:37 UTC, Karnak19 requested changes

2021-07-05 07:37 UTC, Karnak19 commented on src/components/NavBar.tsx/USER.tsx
> +function USER({ newReport, Home, report, settings, handleClose }: ISPNavbar): JSX.Element {
Be consistent in naming convention (i.e. camelCase)

2021-07-05 07:37 UTC, Karnak19 commented on src/components/NavBar.tsx/sideBar.tsx
> +interface sideBarProps {
PascalCase for interfaces

2021-07-05 07:37 UTC, Karnak19 commented on src/components/companies/CompanyDetails.tsx
> +    );
Don't you have a Loader and Error component ?

2021-07-05 07:37 UTC, Karnak19 commented on src/components/companies/ListsCompanies.tsx
> +    );
Same here, Loading & Error components ?

2021-07-05 07:37 UTC, Karnak19 commented on src/components/head.tsx
>  function Head({ setIsSidebarVisible, setSideBarClass }: IProps): JSX.Element {
File naming (i.e. PascalCase)

2021-07-05 07:37 UTC, Karnak19 commented on tailwind.config.js
> +      // },
dead code

2021-07-05 07:37 UTC, Karnak19 commented on tailwind.config.js
> +        // bgImg: "url('./media/images/bgAevisioGray.png')",
dead code

2021-07-05 13:53 UTC, merged